from tkinter import *
from tkinter import filedialog
from tkinter import messagebox
import csv


class App:
    def __init__(self, master):
        self.filename = ""
        self.csvFines = ""
        self.csvOverdues = ""
        self.outputCsv = ""

        master.minsize(width=360, height=240)
        master.title("Allan's time saving barcode thingy")
        frame = Frame(master)
        frame.pack()

        self.cleanButton = Button(
            frame, text="Clean a barcode file", command=self.clean_barcode_file
        )
        self.cleanButton.pack(side=LEFT)

        self.button = Button(
            frame, text="Exit", fg="red", command=frame.quit
        )
        self.button.pack(side=LEFT)

    def clean_barcode_file(self):
        self.filename = filedialog.askopenfilename(initialdir="T:/Library/Data/STOCKTAKE",
                                                   title="Pick a file to clean",
                                                   filetypes=(("txt files", "*.txt"), ("All files", "*.*")))
        with open(self.filename, "r") as file:
            content = file.readlines()
        content = [x.strip() for x in content]
        print(content)
        for i in range(len(content)):
            # Remove non alphanumeric endings generated by the crappy scanner
            for j in range(len(content[i])):
                if not str.isalnum(content[i][j]):
                    content[i] = content[i][:j]

            # Remove trailing letters from the end if they are not an X
            for k in range(len(content[i])-1, 0, -1):
                if not str.isdigit(content[i][k]) and content[i][k] != "X":
                    content[i] = content[i][:k]

            # If it starts with A7, length = 7 characters
            if content[i].startswith("A7"):
                content[i] = content[i][:7]

            # If it starts with A007, length = 9 characters
            if content[i].startswith("A007"):
                content[i] = content[i][:9]

            # If it starts with A0006, length = 10 characters
            if content[i].startswith("A0006"):
                content[i] = content[i][:10]

            # If it starts with A006, length = 9 characters
            if content[i].startswith("A006"):
                content[i] = content[i][:9]

        with open((self.filename[:-4] + " Clean" + ".txt"), "w") as outfile:
            for line in content:
                outfile.write(line + "\n")

        messagebox.showinfo("Done", "File successfully cleaned!")


root = Tk()

app = App(root)

root.mainloop()
root.destroy()
